# Generated by Django 3.1.2 on 2021-11-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='boss',
            field=models.CharField(default='A', max_length=150),
            preserve_default=False,
        ),
    ]
